DESC EMP;

SELECT EMPNO 사원번호, ENAME 이름, HIREDATE 입사일, SAL 급여
FROM EMP
WHERE ENAME LIKE 'K%';

SELECT *
FROM EMP
WHERE DATE_FORMAT(HIREDATE, '%Y') = 2000;

SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

SELECT ENAME 이름, DEPTNO 부서번호, SAL 월급
FROM EMP
WHERE DEPTNO = 30 AND SAL >=1500;

SELECT EMPNO 사원번호, DEPTNO 부서번호
FROM EMP
WHERE DEPTNO = 30
ORDER BY EMPNO;

SELECT SAL 급여, EMPNO 사원번호
FROM EMP
ORDER BY SAL DESC;

SELECT DEPTNO 부서번호, SAL 급여, EMPNO 사원번호
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;

SELECT DEPTNO 부서번호, SAL 급여, ENAME 이름
FROM EMP
ORDER BY DEPTNO DESC, ENAME ASC, SAL DESC;

SELECT ENAME 이름, SAL 급여, SAL * COMM / 100 "커미션 금액", SAL+COMM 총액
FROM EMP
WHERE COMM IS NOT NULL
ORDER BY 총액 DESC;

SELECT ENAME 이름, SAL 급여, SAL * 0.13 "보너스 금액", DEPTNO 부서번호
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME 이름, SAL 급여, ROUND(SAL / 60 ,1) "시간당 임금"
FROM EMP
WHERE DEPTNO = 20;

SELECT ENAME 이름, SAL 급여, ROUND(SAL * 0.15 ,2) 회비
FROM EMP
WHERE SAL BETWEEN 1500 AND 3000;

SELECT ENAME 이름, SAL 급여, SAL * 0.9 실수령액
FROM EMP
ORDER BY SAL DESC;

SELECT LCASE(LEFT(ENAME, 3)) 이름
FROM EMP
WHERE CHAR_LENGTH(ENAME) >=6; -- CHAR_LENGTH를 사용해서 길이를 구함

SELECT AVG(SAL) 평균, MAX(SAL) 최고, MIN(SAL) 최저, COUNT(*) 인원수
FROM EMP
WHERE DEPTNO = 10;

SELECT DEPTNO 부서번호, JOB 업무명, COUNT(JOB) 인원수
FROM EMP
GROUP BY DEPTNO, JOB;

SELECT JOB 업무명, COUNT(*) 인원수
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 4;

SELECT ENAME 이름, HIREDATE 입사일, TO_DAYS(NOW())-TO_DAYS(HIREDATE) 근무일수
FROM EMP; -- DATEDIFF써도됌

SELECT ENAME 이름, DATE_FORMAT(NOW(), '%Y')-DATE_FORMAT(HIREDATE, '%Y') 근속년수
FROM EMP;